In [32]:
import tensorflow
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import Adam

#Random seeds
import random as rn
def seed_everything(seed=12):
    rn.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    tensorflow.random.set_seed(seed)
    session_conf = tensorflow.compat.v1.ConfigProto(
        intra_op_parallelism_threads=1,
        inter_op_parallelism_threads=1
    )
    sess = tensorflow.compat.v1.Session(graph=tensorflow.compat.v1.get_default_graph(), config=session_conf)
    tensorflow.compat.v1.keras.backend.set_session(sess)
seed_everything(12)

#Setting directly
os.chdir("C:/Users/prajj/OneDrive/Desktop/capstoneserver/model/Predicting-sensory-evaluation-of-spinach-freshness-using-machine-learning-model-and-digital-images/Attached_file")
df = pd.read_csv('data/train_feature.csv', index_col=0)
X_train = df.drop(['label'],axis=1)
y_train = df['label'].astype(int)
df = pd.read_csv('data/test_feature.csv', index_col=0)
X_test = df.drop(['label'],axis=1)
y_test = df['label'].astype(int)
print(len(X_train), len(X_test), len(y_train), len(y_test))

#Scaler
scaler = StandardScaler()
scaler.fit(X_train)
scale_train =scaler.transform(X_train)
scale_test =scaler.transform(X_test)

#Class name
y_train_ca =y_train-1
y_train_ca =to_categorical(y_train_ca, num_classes=4)
y_test_ca = y_test-1
#Import collections
class_weight ={0:1, 1:0.46, 2:0.38, 3:3.6}
model = Sequential()
# Use scikit-learn to grid search the batch size and epochs
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.wrappers.scikit_learn import KerasClassifier
# Function to create model, required for KerasClassifier
def create_model(learn_rate=0.01,activation='relu',dropout_rate=0.1):
#Create model
    model = Sequential()
    model.add(Dense(32, input_dim=X_test.shape[1], activation=activation))
    model.add(Dropout(dropout_rate))
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(64, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(4, activation='softmax'))
    # Compile model
    optimizer = Adam(lr=learn_rate)
    model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model
#Create model
model = KerasClassifier(build_fn=create_model, verbose=0)
#Define the grid search parameters
batch_size = [30, 60, 90, 120]
epochs = [60, 80, 120, 150]
learn_rate = [0.001]
dropout_rate = [0.1]
activation = ['sigmoid','relu']
param_grid = dict(batch_size=batch_size, epochs=epochs,learn_rate=learn_rate, activation=activation, dropout_rate=dropout_rate)

grid = GridSearchCV(estimator=model, param_grid=param_grid ,n_jobs=-1, cv=5)
grid_result = grid.fit(scale_train, y_train_ca, verbose=1, class_weight=class_weight)
#Summarize results
print("Best: %.2f%% using %s" % (grid_result.best_score_, grid_result.best_params_))
y_pred_train = grid_result.predict(scale_train)
y_pred_test = grid_result.predict(scale_test)  
train_score = accuracy_score(y_train.values-1,y_pred_train)
test_score = accuracy_score(y_test.values-1,y_pred_test)
print("\n%s: %.2f%%" % ('val_acc', grid_result.best_score_*100))
print('train_score: '+str("{0:.2f}".format(train_score)))
print('test_score: '+str("{0:.2f}".format(test_score)))
print("train_cm:\n", confusion_matrix(y_train.values-1, y_pred_train))
print("test_cm:\n", confusion_matrix(y_test.values-1, y_pred_test))




836 209 836 209


C:\Users\prajj\Anaconda3\lib\site-packages\ipykernel_launcher.py:72: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
C:\Users\prajj\Anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Epoch 1/120
10/10 [==============================] - 2s 6ms/step - loss: 0.8657 - accuracy: 0.2297
Epoch 2/120
10/10 [==============================] - 0s 7ms/step - loss: 0.7347 - accuracy: 0.5167
Epoch 3/120
10/10 [==============================] - 0s 7ms/step - loss: 0.6398 - accuracy: 0.4581
Epoch 4/120
10/10 [==============================] - 0s 7ms/step - loss: 0.5763 - accuracy: 0.5060
Epoch 5/120
10/10 [==============================] - 0s 5ms/step - loss: 0.5290 - accuracy: 0.5383
Epoch 6/120
10/10 [==============================] - 0s 4ms/step - loss: 0.4910 - accuracy: 0.6100
Epoch 7/120
10/10 [==============================] - 0s 5ms/step - loss: 0.4568 - accuracy: 0.6172
Epoch 8/120
10/10 [==============================] - 0s 6ms/step - loss: 0.4390 - accuracy: 0.6328
Epoch 9/120
10/10 [==============================] - 0s 5ms/step - loss: 0.4059 - accuracy: 0.6411
Epoch 10/120
10/10 [==============================] - 0s 4ms/step - loss: 0.3761 - accuracy: 0.7261
Epoch 11/

10/10 [==============================] - 0s 3ms/step - loss: 0.0242 - accuracy: 0.9809
Epoch 84/120
10/10 [==============================] - 0s 3ms/step - loss: 0.0299 - accuracy: 0.9773
Epoch 85/120
10/10 [==============================] - 0s 3ms/step - loss: 0.0488 - accuracy: 0.9761
Epoch 86/120
10/10 [==============================] - 0s 4ms/step - loss: 0.0570 - accuracy: 0.9677
Epoch 87/120
10/10 [==============================] - 0s 8ms/step - loss: 0.0434 - accuracy: 0.9629
Epoch 88/120
10/10 [==============================] - 0s 2ms/step - loss: 0.0438 - accuracy: 0.9761
Epoch 89/120
10/10 [==============================] - 0s 3ms/step - loss: 0.0341 - accuracy: 0.9713
Epoch 90/120
10/10 [==============================] - 0s 3ms/step - loss: 0.0400 - accuracy: 0.9821
Epoch 91/120
10/10 [==============================] - 0s 3ms/step - loss: 0.0306 - accuracy: 0.9773
Epoch 92/120
10/10 [==============================] - 0s 3ms/step - loss: 0.0332 - accuracy: 0.9725
Epoch 93/120


In [4]:
import pickle


# Assuming you have a trained model 'model'
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)


In [9]:
pip install jolib

Note: you may need to restart the kernel to use updated packages.


In [11]:
import joblib

#save your model or results
joblib.load(gri 'model_file_name.pkl')



INFO:tensorflow:Assets written to: ram://35e776df-1623-462c-ae63-b940eb396aaf/assets


['model_file_name.pkl']

In [29]:
#Importing required packages.
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import GridSearchCV

#Setting directly
os.chdir("C:/Users/prajj/OneDrive/Desktop/capstoneserver/model/Predicting-sensory-evaluation-of-spinach-freshness-using-machine-learning-model-and-digital-images/Attached_file")

#Loading training and test dataset
df = pd.read_csv('data/train_feature.csv', index_col=0)
X_train = df.drop(['label'],axis=1)
y_train = df['label'].astype(int)
df = pd.read_csv('data/test_feature.csv', index_col=0)
X_test = df.drop(['label'],axis=1)
y_test = df['label'].astype(int)
print(len(X_train), len(X_test), len(y_train), len(y_test))

#Scaler
scaler = StandardScaler()
scaler.fit(X_train)
scale_train =scaler.transform(X_train)
scale_test =scaler.transform(X_test)
#pipelines
pipelines = {
        "svc_rbf": make_pipeline(SVC(class_weight='balanced',random_state=12))
}
svc_rbf_hyperparameters = {
    'svc__kernel': ['rbf'],
    'svc__C': np.arange(1,10,1),
    'svc__gamma':np.logspace(-4, 0, 5, base=10),
    "svc__random_state":[12]
}
hyperparameters = {
        "svc_rbf":svc_rbf_hyperparameters
}

# Create empty dictionary called fitted_models
fitted_models = {}
# Loop through model pipelines, tuning each one and saving it to fitted_models
for name, pipeline in pipelines.items():
    # Create cross-validation object from pipeline and hyperparameters
    model = GridSearchCV(pipeline, hyperparameters[name], cv= 5, n_jobs= -1,scoring='accuracy')    
    # Fit model on X_train, y_train
    model.fit(scale_train, y_train)    
    # Store model in fitted_models[name] 
    fitted_models[name] = model    
    # Print '{name} has been fitted'
    print(name, 'has been fitted.')
op=''    
for name, model in fitted_models.items():
    op=model
    print("Cross validation", "{0:.2f}".format(model.best_score_))
    pred = model.predict(scale_train)
    C = confusion_matrix(y_train, pred)
    print('Acc train:', "{0:.2f}".format(accuracy_score(y_train, pred)))
    print("Normalized cm train:\n", C.astype('float') / C.sum(axis=1)[:, np.newaxis])
for name, model in fitted_models.items():
    print(name)
    print("-----------")
    pred = model.predict(scale_test)
    C = confusion_matrix(y_test, pred)
    print('Acc test:', "{0:.2f}".format(accuracy_score(y_test, pred)))
    print("Normalized cm test:\n", C.astype('float') / C.sum(axis=1)[:, np.newaxis])
    print("Best Hyper Parameters:\n",model.best_params_)

836 209 836 209
svc_rbf has been fitted.
Cross validation 0.71
Acc train: 1.00
Normalized cm train:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
svc_rbf
-----------
Acc test: 0.68
Normalized cm test:
 [[0.55882353 0.41176471 0.02941176 0.        ]
 [0.04       0.73333333 0.22666667 0.        ]
 [0.         0.24444444 0.75555556 0.        ]
 [0.         0.         0.9        0.1       ]]
Best Hyper Parameters:
 {'svc__C': 3, 'svc__gamma': 0.01, 'svc__kernel': 'rbf', 'svc__random_state': 12}


In [31]:
y_test

0      2
1      4
2      1
3      2
4      1
      ..
204    2
205    3
206    3
207    3
208    3
Name: label, Length: 209, dtype: int32

In [4]:
import joblib
gs=fitted_models['svc_rbf']
gs

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('svc',
                                        SVC(class_weight='balanced',
                                            random_state=12))]),
             n_jobs=-1,
             param_grid={'svc__C': array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
                         'svc__gamma': array([1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00]),
                         'svc__kernel': ['rbf'], 'svc__random_state': [12]},
             scoring='accuracy')

In [28]:
gs.predict(X_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
joblib.dump(fitted, 'models_grid.pkl')

['models_grid.pkl']

In [17]:
first_row=X_train.iloc[0]
a=np.array(first_row)
a=a.reshape(1,-1)

In [22]:
loaded_model = joblib.load('models_grid.pkl')

In [33]:
loaded_model.predict(scale_test)

array([2, 3, 1, 2, 1, 3, 3, 1, 1, 2, 2, 3, 3, 3, 3, 2, 3, 3, 3, 2, 2, 2,
       2, 1, 2, 2, 3, 1, 3, 2, 2, 2, 3, 2, 1, 3, 3, 3, 3, 2, 2, 2, 3, 2,
       3, 1, 2, 2, 2, 2, 1, 2, 2, 3, 3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3,
       2, 3, 3, 3, 3, 2, 3, 2, 1, 2, 3, 3, 3, 2, 3, 1, 3, 1, 2, 1, 2, 3,
       3, 3, 2, 2, 3, 2, 2, 3, 3, 2, 1, 2, 3, 2, 2, 2, 3, 1, 2, 2, 2, 3,
       3, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       2, 2, 3, 3, 3, 3, 2, 3, 2, 3, 1, 2, 2, 1, 3, 2, 2, 2, 2, 3, 3, 3,
       3, 2, 2, 2, 2, 2, 2, 4, 2, 1, 2, 3, 1, 3, 3, 2, 2, 1, 3, 3, 1, 3,
       3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 2, 2, 3, 3, 2, 2, 3, 2, 2, 2,
       2, 2, 1, 2, 2, 3, 3, 3, 3, 2, 3])

In [34]:
X_train

gry          b           g          r          h           s  \
0    80.279621  34.183760   94.398857  70.153900  42.267678  165.889913   
1    77.393634  39.465580   89.203236  68.729331  42.560133  143.786610   
2    82.039218  39.302562   95.349459  72.226219  42.612996  151.611681   
3    67.438145  38.150518   77.346432  59.177782  44.345727  129.958599   
4    71.649112  34.464703   84.537522  60.543012  44.644150  151.042385   
..         ...        ...         ...        ...        ...         ...   
831  87.062305  42.953084  102.248729  74.060646  44.544899  150.612683   
832  80.722945  30.541489   97.172116  67.565005  43.635659  174.571890   
833  58.633316  41.822711   65.282357  52.016893  47.702329   94.790345   
834  76.629676  43.004951   86.135709  70.765679  40.971657  131.501800   
835  77.544773  35.287250   91.835958  65.596505  44.165027  158.776908   

              v           l           a          bl  ...  orb_v11  orb_v12  \
0     94.401796   94.009250  108.220617  158.627226  ...     12.0     12.0   
1     89.224835   89.600067  110.960220  153.843064  ...      7.0     13.0   
2     95.349459   95.417023  109.145027  156.659661  ...     24.0     14.0   
3     77.348153   77.299217  113.208954  148.616605  ...     17.0     37.0   
4     84.539253   83.959163  109.443827  153.688769  ...     10.0     16.0   
..          ...         ...         ...         ...  ...      ...      ...   
831  102.271828  101.646390  106.728786  157.587712  ...     24.0     23.0   
832   97.180150   95.961302  105.377963  161.036018  ...     54.0      6.0   
833   65.282910   65.775035  117.519573  140.586797  ...     14.0     23.0   
834   86.165952   87.282129  113.946320  150.938193  ...      2.0     27.0   
835   91.843084   91.134910  107.729195  156.696574  ...     14.0      7.0   

     orb_v13  orb_v14  orb_v15  orb_v16  orb_v17  orb_v18  orb_v19  orb_v20  
0       19.0     24.0     10.0      3.0     35.0     19.0     14.0     24.0  
1       10.0     57.0     28.0      3.0      6.0     10.0     12.0     19.0  
2       35.0     25.0     11.0     11.0     46.0     10.0     30.0     12.0  
3       17.0     42.0     21.0     12.0     12.0     10.0      8.0     12.0  
4       12.0     33.0     15.0      2.0     10.0     14.0     21.0     23.0  
..       ...      ...      ...      ...      ...      ...      ...      ...  
831     24.0     11.0      7.0     52.0      9.0     14.0     17.0     20.0  
832     32.0     17.0      6.0     22.0     20.0     37.0      4.0     15.0  
833      9.0     40.0     15.0     11.0      7.0     12.0     37.0     31.0  
834     21.0     42.0     20.0      3.0     26.0     12.0     19.0     33.0  
835     22.0     12.0      9.0     29.0      5.0     24.0      3.0     11.0  

[836 rows x 230 columns]